Repository ansatpro/ansatpro-web, pull requests merged in 2025-05, with the labels that each got.

#57 Pull Request: Add Frontend Function Integration, Appwrite Configuration, and Utility Styling
  functions/HowToConnectToFunction.js
  functions/appwrite.js
  functions/utils.js
  src/app/appwrite.js
Labels: Medium Priority, Frontend Component, feature, backend

#63 Add user_metadata_function to manage post-registration user profile and avatar storage with its documentation
  functions/add_metadata/README.md
  functions/add_metadata/src/main.js
  functions/user_metadata_function/.gitignore
  functions/user_metadata_function/.gitkeep
  functions/user_metadata_function/.prettierrc.json
  functions/user_metadata_function/README.md
  functions/user_metadata_function/package-lock.json
  functions/user_metadata_function/package.json
  functions/user_metadata_function/src/main.js
Labels: documentation, enhancement, feature, backend

#65 implement Login, Register, Forgot Password, and Reset Password pages
  src/app/auth/forgot-password/page.js
  src/app/auth/login/page.js
  src/app/auth/register/page.js
  src/app/auth/reset-password/page.js
Labels: User Management, feature, auth
